# Generated by Django 3.2.3 on 2021-05-30 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_temp', models.IntegerField(max_length=50, verbose_name='min_temp')),
                ('max_temp', models.IntegerField(max_length=50, verbose_name='max_temp')),
            ],
            options={
                'verbose_name': 'Диапазон температур',
                'verbose_name_plural': 'Диапазоны температур',
            },
        ),
        migrations.CreateModel(
            name='WeatherType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200, verbose_name='тип погоды')),
            ],
            options={
                'verbose_name': 'Тип погоды',
                'verbose_name_plural': 'Типы погоды',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250, verbose_name='url')),
                ('redirect_url', models.CharField(blank=True, default='', max_length=250, verbose_name='ссылка на магазин')),
                ('is_clear', models.BooleanField(default=True, verbose_name='clear')),
                ('is_cloud', models.BooleanField(default=True, verbose_name='cloud')),
                ('is_partly_cloud', models.BooleanField(default=True, verbose_name='partly_cloud')),
                ('is_rain', models.BooleanField(default=True, verbose_name='rain')),
                ('temp_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_api.temprange')),
                ('weather_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_api.weathertype')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
