# Generated by Django 3.2.3 on 2021-05-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0002_auto_20210530_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200, verbose_name='тип погоды')),
            ],
            options={
                'verbose_name': 'Тип погоды',
                'verbose_name_plural': 'Типы погоды',
            },
        ),
        migrations.AddField(
            model_name='image',
            name='weather_type',
            field=models.ManyToManyField(blank=True, default=None, to='weather_api.WeatherType'),
        ),
    ]
