# Generated by Django 3.2.3 on 2021-05-30 18:45

from django.db import migrations, models
import weather_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0003_auto_20210530_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temprange',
            options={'verbose_name': 'Диапазон температур (включительно)', 'verbose_name_plural': 'Диапазоны температур'},
        ),
        migrations.RemoveField(
            model_name='image',
            name='is_clear',
        ),
        migrations.RemoveField(
            model_name='image',
            name='is_cloud',
        ),
        migrations.RemoveField(
            model_name='image',
            name='is_partly_cloud',
        ),
        migrations.RemoveField(
            model_name='image',
            name='is_rain',
        ),
        migrations.AlterField(
            model_name='image',
            name='weather_type',
            field=models.ManyToManyField(blank=True, default=weather_api.models.allWeatherType, to='weather_api.WeatherType'),
        ),
    ]
